// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/interior-designing": {
    params: {};
  };
  "/services": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/cart": {
    params: {};
  };
  "/order-confirmation": {
    params: {};
  };
  "/admin/login": {
    params: {};
  };
  "/admin/dashboard": {
    params: {};
  };
  "/admin/products": {
    params: {};
  };
  "/admin/products/create": {
    params: {};
  };
  "/admin/products/edit/:id": {
    params: {
      "id": string;
    };
  };
  "/api/admin/logout": {
    params: {};
  };
  "/api/admin/products": {
    params: {};
  };
  "/api/admin/products/:id": {
    params: {
      "id": string;
    };
  };
  "/api/admin/products/:id/delete": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/interior-designing" | "/services" | "/products" | "/cart" | "/order-confirmation" | "/admin/login" | "/admin/dashboard" | "/admin/products" | "/admin/products/create" | "/admin/products/edit/:id" | "/api/admin/logout" | "/api/admin/products" | "/api/admin/products/:id" | "/api/admin/products/:id/delete";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/interior-designing.tsx": {
    id: "routes/interior-designing";
    page: "/interior-designing";
  };
  "routes/services.tsx": {
    id: "routes/services";
    page: "/services";
  };
  "routes/products.tsx": {
    id: "routes/products";
    page: "/products";
  };
  "routes/cart.tsx": {
    id: "routes/cart";
    page: "/cart";
  };
  "routes/order-confirmation.tsx": {
    id: "routes/order-confirmation";
    page: "/order-confirmation";
  };
  "routes/admin/login.tsx": {
    id: "routes/admin/login";
    page: "/admin/login";
  };
  "routes/admin/dashboard.tsx": {
    id: "routes/admin/dashboard";
    page: "/admin/dashboard";
  };
  "routes/admin/products/index.tsx": {
    id: "routes/admin/products/index";
    page: "/admin/products";
  };
  "routes/admin/products/create.tsx": {
    id: "routes/admin/products/create";
    page: "/admin/products/create";
  };
  "routes/admin/products/edit.$id.tsx": {
    id: "routes/admin/products/edit.$id";
    page: "/admin/products/edit/:id";
  };
  "routes/api/admin/logout.ts": {
    id: "routes/api/admin/logout";
    page: "/api/admin/logout";
  };
  "routes/api/admin/products.ts": {
    id: "routes/api/admin/products";
    page: "/api/admin/products";
  };
  "routes/api/admin/products.$id.ts": {
    id: "routes/api/admin/products.$id";
    page: "/api/admin/products/:id";
  };
  "routes/api/admin/products.$id.delete.ts": {
    id: "routes/api/admin/products.$id.delete";
    page: "/api/admin/products/:id/delete";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/interior-designing": typeof import("./app/routes/interior-designing.tsx");
  "routes/services": typeof import("./app/routes/services.tsx");
  "routes/products": typeof import("./app/routes/products.tsx");
  "routes/cart": typeof import("./app/routes/cart.tsx");
  "routes/order-confirmation": typeof import("./app/routes/order-confirmation.tsx");
  "routes/admin/login": typeof import("./app/routes/admin/login.tsx");
  "routes/admin/dashboard": typeof import("./app/routes/admin/dashboard.tsx");
  "routes/admin/products/index": typeof import("./app/routes/admin/products/index.tsx");
  "routes/admin/products/create": typeof import("./app/routes/admin/products/create.tsx");
  "routes/admin/products/edit.$id": typeof import("./app/routes/admin/products/edit.$id.tsx");
  "routes/api/admin/logout": typeof import("./app/routes/api/admin/logout.ts");
  "routes/api/admin/products": typeof import("./app/routes/api/admin/products.ts");
  "routes/api/admin/products.$id": typeof import("./app/routes/api/admin/products.$id.ts");
  "routes/api/admin/products.$id.delete": typeof import("./app/routes/api/admin/products.$id.delete.ts");
};