// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/interior-designing": {
    params: {};
  };
  "/services": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/cart": {
    params: {};
  };
  "/order-confirmation": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/interior-designing" | "/services" | "/products" | "/cart" | "/order-confirmation";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/interior-designing.tsx": {
    id: "routes/interior-designing";
    page: "/interior-designing";
  };
  "routes/services.tsx": {
    id: "routes/services";
    page: "/services";
  };
  "routes/products.tsx": {
    id: "routes/products";
    page: "/products";
  };
  "routes/cart.tsx": {
    id: "routes/cart";
    page: "/cart";
  };
  "routes/order-confirmation.tsx": {
    id: "routes/order-confirmation";
    page: "/order-confirmation";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/interior-designing": typeof import("./app/routes/interior-designing.tsx");
  "routes/services": typeof import("./app/routes/services.tsx");
  "routes/products": typeof import("./app/routes/products.tsx");
  "routes/cart": typeof import("./app/routes/cart.tsx");
  "routes/order-confirmation": typeof import("./app/routes/order-confirmation.tsx");
};